$_SERVER['PHP_AUTH_PW'] isn't always sent
Nachtzuster/BirdNET-Pi pull request #244
Opened 2024-11-28 02:20 UTC by ashmckenzie

This PR aims to fix https://github.com/Nachtzuster/BirdNET-Pi/issues/243.

I previously never provided a password which worked OK,  but `isset($_SERVER['PHP_AUTH_PW'])` now returns `false`, which means `if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {` returns `false` and so returns an overall result of `false` (which fails auth).

The change below removes the `if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {` check entirely as it seems to work correctly without it.

I honestly don't know why this is now necessary as I can't see any recent code changes, perhaps a recent PHP upgrade caused this?

2024-11-30 18:20 UTC, Nachtzuster requested changes
Pretty weird bug indeed, maybe the php update from 8.2.24 to 8.2.26? can't really find anything in the release notes or a (quick) search on their github.

Since we don't really understand the change in behavior, I'd like a minimal change. ie just remove the isset() check for the password

2024-11-30 18:20 UTC, Nachtzuster commented on scripts/common.php
> +  return ($_SERVER['PHP_AUTH_PW'] == $config['CADDY_PWD'] && $_SERVER['PHP_AUTH_USER'] == 'birdnet');
```suggestion
  $ret = false;
  if (isset($_SERVER['PHP_AUTH_USER'])) {
    $config = get_config();
    $ret = ($_SERVER['PHP_AUTH_PW'] == $config['CADDY_PWD'] && $_SERVER['PHP_AUTH_USER'] == 'birdnet');
  }
  return $ret;
```

2024-12-01 05:34 UTC, ashmckenzie commented on scripts/common.php
> +  return ($_SERVER['PHP_AUTH_PW'] == $config['CADDY_PWD'] && $_SERVER['PHP_AUTH_USER'] == 'birdnet');
OK :+1:

2024-12-01 08:33 UTC, merged

2024-12-01 08:33 UTC, Nachtzuster commented
@ashmckenzie Thanks!